### ISSUE TITLE
Spawn new window for ability tracker/rotation feeder

### ISSUE THREAD

**Issue by Raswanson01** [Raswanson01/rs3mate#6]
- [ ] Add button to home page and rotation builder
- [ ] Create component to run Queue
- [ ] Load selected rotation config
